version: '3.7'
services:
  jupyterlab:
    build: ./jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./:/root/user/jupyterlab
    working_dir: /root/user/jupyterlab
    command: sh /run.sh